// PROTOTYPE — throwaway after issue #25 chooses a direction.
// Three admin-screen variants, switchable via ?variant=, on the existing /admin route.

import {
  ArrowRightIcon,
  CheckCircle2Icon,
  Clock3Icon,
  DatabaseIcon,
  PlusIcon,
  SearchIcon,
  ShieldCheckIcon,
  TriangleAlertIcon,
  UsersIcon,
} from "lucide-react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type { SyncRun } from "@/lib/db/schema";
import type { LinkListing } from "@/lib/identity";
import type { FlaggedPerson, UnlinkedPerson } from "@/lib/sync";

type Props = {
  lastRun: SyncRun | null;
  queue: UnlinkedPerson[];
  flagged: FlaggedPerson[];
  links: LinkListing[];
};

export function AdminScreenPrototype({ variant, ...props }: Props & { variant: "A" | "B" | "C" }) {
  if (variant === "A") return <VariantA {...props} />;
  if (variant === "B") return <VariantB {...props} />;
  return <VariantC {...props} />;
}

function VariantA(props: Props) {
  const attention = props.queue.length + props.flagged.length;
  return (
    <main className="flex flex-col gap-6 pb-20">
      <PageHeading eyebrow="Prototype A · Dashboard" title="Good morning" description="Start with data confidence, then show only work that needs a decision." />
      <SyncHero lastRun={props.lastRun} />
      <div className="grid gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Needs attention</CardTitle>
            <CardDescription>{attention ? `${attention} items generated by sync.` : "No admin work waiting."}</CardDescription>
            <CardAction><Badge variant={attention ? "default" : "secondary"}>{attention}</Badge></CardAction>
          </CardHeader>
          <CardContent className="flex flex-col gap-5">
            <QueuePreview queue={props.queue} />
            <Separator />
            <FlaggedPreview flagged={props.flagged} />
          </CardContent>
          <CardFooter><Button type="button" variant="outline">Review all work <ArrowRightIcon data-icon="inline-end" /></Button></CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Portal accounts</CardTitle>
            <CardDescription>The allowlist: who can sign in.</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-4xl font-semibold tracking-tight">{props.links.length}</p>
            <p className="mt-2 text-sm text-muted-foreground">{adminCount(props.links)} admins · {unlinkedAccountCount(props.links)} without a FACTS person</p>
          </CardContent>
          <CardFooter className="flex gap-2">
            <Button type="button" variant="outline">Browse</Button>
            <Button type="button"><PlusIcon data-icon="inline-start" /> Add</Button>
          </CardFooter>
        </Card>
      </div>
    </main>
  );
}

function VariantB(props: Props) {
  return (
    <main className="grid gap-6 pb-20 lg:grid-cols-[15rem_minmax(0,1fr)]">
      <aside className="flex flex-col gap-5 rounded-xl border bg-card p-5">
        <div>
          <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Prototype B</p>
          <h1 className="mt-1 text-xl font-semibold">Admin work</h1>
        </div>
        <Separator />
        <StatusRow icon={DatabaseIcon} label="FACTS data" value={syncShortStatus(props.lastRun)} />
        <StatusRow icon={Clock3Icon} label="Last sync" value={props.lastRun?.finishedAt ? formatWhen(props.lastRun.finishedAt) : "Never"} />
        <StatusRow icon={UsersIcon} label="Portal accounts" value={String(props.links.length)} />
        <div className="mt-auto flex flex-col gap-2">
          <Button type="button" variant="outline">Sync now</Button>
          <Button type="button"><PlusIcon data-icon="inline-start" /> Add account</Button>
        </div>
      </aside>
      <section className="flex min-w-0 flex-col gap-5">
        <div>
          <h2 className="text-3xl font-semibold tracking-tight">Inbox</h2>
          <p className="text-muted-foreground">One queue for decisions created by sync.</p>
        </div>
        {props.queue.length === 0 && props.flagged.length === 0 ? (
          <Alert><CheckCircle2Icon /><AlertTitle>All caught up</AlertTitle><AlertDescription>No links or inactive records need review.</AlertDescription></Alert>
        ) : (
          <div className="flex flex-col gap-3">
            {props.queue.map((person) => <InboxUnlinked key={person.personId} person={person} />)}
            {props.flagged.map((person) => <InboxFlagged key={`${person.flaggedByRunId}-${person.personId}`} person={person} />)}
          </div>
        )}
        <Card>
          <CardHeader>
            <CardTitle>Account directory</CardTitle>
            <CardDescription>Kept out of the work queue. Search the {props.links.length}-account allowlist when needed.</CardDescription>
          </CardHeader>
          <CardContent className="flex gap-2">
            <Input aria-label="Search portal accounts" placeholder="Search name or Google account…" />
            <Button type="button" variant="outline" size="icon" aria-label="Search"><SearchIcon /></Button>
          </CardContent>
        </Card>
      </section>
    </main>
  );
}

function VariantC(props: Props) {
  return (
    <main className="flex flex-col gap-4 pb-20">
      <PageHeading eyebrow="Prototype C · Command center" title="Portal administration" description="Dense, scan-first, one surface. Accounts remain on-page but bounded." />
      <div className="grid gap-3 sm:grid-cols-4">
        <Metric icon={DatabaseIcon} label="Sync" value={syncShortStatus(props.lastRun)} />
        <Metric icon={Clock3Icon} label="Last run" value={props.lastRun?.finishedAt ? formatWhen(props.lastRun.finishedAt) : "Never"} />
        <Metric icon={TriangleAlertIcon} label="Needs attention" value={String(props.queue.length + props.flagged.length)} />
        <Metric icon={ShieldCheckIcon} label="Portal accounts" value={String(props.links.length)} />
      </div>
      <div className="flex flex-wrap gap-2">
        <Button type="button">Sync now</Button>
        <Button type="button" variant="outline"><PlusIcon data-icon="inline-start" /> Add portal account</Button>
        <div className="ml-auto flex min-w-64 gap-2">
          <Input aria-label="Search portal accounts" placeholder="Search accounts…" />
          <Button type="button" variant="outline" size="icon" aria-label="Search"><SearchIcon /></Button>
        </div>
      </div>
      <Card size="sm">
        <CardHeader>
          <CardTitle>Admin work</CardTitle>
          <CardDescription>Awaiting links and inactive FACTS records, together.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader><TableRow><TableHead>Type</TableHead><TableHead>Person</TableHead><TableHead>Meaning</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader>
            <TableBody>
              {props.queue.map((person) => <WorkTableUnlinked key={person.personId} person={person} />)}
              {props.flagged.map((person) => <WorkTableFlagged key={`${person.flaggedByRunId}-${person.personId}`} person={person} />)}
              {!props.queue.length && !props.flagged.length && <TableRow><TableCell colSpan={4} className="text-center text-muted-foreground">Nothing needs attention.</TableCell></TableRow>}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      <Card size="sm">
        <CardHeader>
          <CardTitle>Portal accounts</CardTitle>
          <CardDescription>Showing 8 of {props.links.length}. Search opens the working set; the full list never expands the landing page.</CardDescription>
        </CardHeader>
        <CardContent><AccountsTable links={props.links.slice(0, 8)} /></CardContent>
        <CardFooter><Button type="button" variant="ghost">View all {props.links.length} accounts <ArrowRightIcon data-icon="inline-end" /></Button></CardFooter>
      </Card>
    </main>
  );
}

function SyncHero({ lastRun }: { lastRun: SyncRun | null }) {
  const healthy = lastRun?.outcome === "applied";
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">{healthy ? <CheckCircle2Icon /> : <TriangleAlertIcon />} {syncTitle(lastRun)}</CardTitle>
        <CardDescription>{syncDescription(lastRun)}</CardDescription>
        <CardAction><Button type="button">Sync now</Button></CardAction>
      </CardHeader>
      {lastRun?.outcome === "applied" && (
        <CardContent className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">
          <span>{lastRun.peopleCount} people</span><span>{lastRun.studentCount} students</span><span>{lastRun.staffCount} staff</span><span>{lastRun.unlinkedCount} awaiting a link</span>
        </CardContent>
      )}
    </Card>
  );
}

function QueuePreview({ queue }: { queue: UnlinkedPerson[] }) {
  return <section><h3 className="font-medium">Awaiting a link <Badge variant="secondary">{queue.length}</Badge></h3><p className="mt-1 text-sm text-muted-foreground">People in FACTS who cannot sign in yet.</p>{queue.slice(0, 3).map((person) => <p key={person.personId} className="mt-3 text-sm">{personName(person)} <span className="text-muted-foreground">#{person.personId}</span></p>)}</section>;
}

function FlaggedPreview({ flagged }: { flagged: FlaggedPerson[] }) {
  return <section><h3 className="font-medium">Inactive in FACTS <Badge variant="secondary">{flagged.length}</Badge></h3><p className="mt-1 text-sm text-muted-foreground">Review only. Portal access is unchanged.</p>{flagged.slice(0, 3).map((person) => <p key={`${person.flaggedByRunId}-${person.personId}`} className="mt-3 text-sm">{personName(person)} <span className="text-muted-foreground">#{person.personId}</span></p>)}</section>;
}

function InboxUnlinked({ person }: { person: UnlinkedPerson }) {
  return <Card size="sm"><CardHeader><CardTitle>{personName(person)}</CardTitle><CardDescription>Awaiting a link · FACTS person #{person.personId}</CardDescription><CardAction><Badge>{person.suggestions.length ? "Suggested match" : "Needs account"}</Badge></CardAction></CardHeader><CardFooter><Button type="button" size="sm">{person.suggestions.length ? `Link ${person.suggestions[0].googleEmail}` : "Add portal account"}</Button></CardFooter></Card>;
}

function InboxFlagged({ person }: { person: FlaggedPerson }) {
  return <Card size="sm"><CardHeader><CardTitle>{personName(person)}</CardTitle><CardDescription>Not returned by FACTS sync #{person.flaggedByRunId}. Portal access remains unchanged.</CardDescription><CardAction><Badge variant="outline">Review</Badge></CardAction></CardHeader><CardFooter><Button type="button" variant="outline" size="sm">Clear sync flags</Button></CardFooter></Card>;
}

function WorkTableUnlinked({ person }: { person: UnlinkedPerson }) {
  return <TableRow><TableCell><Badge>Awaiting link</Badge></TableCell><TableCell>{personName(person)} <span className="text-muted-foreground">#{person.personId}</span></TableCell><TableCell className="text-muted-foreground">Cannot sign in yet</TableCell><TableCell className="text-right"><Button type="button" variant="ghost" size="sm">Resolve</Button></TableCell></TableRow>;
}

function WorkTableFlagged({ person }: { person: FlaggedPerson }) {
  return <TableRow><TableCell><Badge variant="outline">Inactive</Badge></TableCell><TableCell>{personName(person)} <span className="text-muted-foreground">#{person.personId}</span></TableCell><TableCell className="text-muted-foreground">Access unchanged</TableCell><TableCell className="text-right"><Button type="button" variant="ghost" size="sm">Review</Button></TableCell></TableRow>;
}

function AccountsTable({ links }: { links: LinkListing[] }) {
  return <Table><TableHeader><TableRow><TableHead>Google account</TableHead><TableHead>FACTS person</TableHead><TableHead>Role</TableHead><TableHead>Admin</TableHead></TableRow></TableHeader><TableBody>{links.map((link) => <TableRow key={link.id}><TableCell className="font-medium">{link.googleEmail}</TableCell><TableCell>{link.factsName ?? (link.factsPersonId ? `#${link.factsPersonId}` : "Not linked")}</TableCell><TableCell>{link.role}</TableCell><TableCell>{link.admin ? "Yes" : "—"}</TableCell></TableRow>)}</TableBody></Table>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof DatabaseIcon; label: string; value: string }) {
  return <Card size="sm"><CardHeader><CardDescription className="flex items-center gap-2"><Icon /> {label}</CardDescription><CardTitle>{value}</CardTitle></CardHeader></Card>;
}

function StatusRow({ icon: Icon, label, value }: { icon: typeof DatabaseIcon; label: string; value: string }) {
  return <div className="flex gap-3"><Icon className="mt-0.5 text-muted-foreground" /><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{value}</p></div></div>;
}

function PageHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <header><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{eyebrow}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-muted-foreground">{description}</p></header>;
}

function syncTitle(lastRun: SyncRun | null) {
  if (!lastRun) return "FACTS has never been synced";
  if (lastRun.outcome === "applied") return "FACTS data is ready";
  if (lastRun.outcome === "failed") return "The last sync failed";
  return "A sync is in progress or was interrupted";
}

function syncShortStatus(lastRun: SyncRun | null) {
  if (!lastRun) return "Never synced";
  if (lastRun.outcome === "applied") return "Ready";
  if (lastRun.outcome === "failed") return "Failed";
  return "Unfinished";
}

function syncDescription(lastRun: SyncRun | null) {
  if (!lastRun) return "Sync before reviewing links or inactive records.";
  const when = formatWhen(lastRun.finishedAt ?? lastRun.startedAt);
  if (lastRun.outcome === "applied") return `Last successful sync ${when}.`;
  if (lastRun.outcome === "failed") return `${when}. The mirror was left unchanged. ${lastRun.detail ?? ""}`;
  return `Started ${when}; reload to check its outcome.`;
}

const personName = (person: { firstName: string | null; lastName: string | null }) => [person.firstName, person.lastName].filter(Boolean).join(" ") || "(no name)";
const formatWhen = (at: Date) => at.toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
const adminCount = (links: LinkListing[]) => links.filter((link) => link.admin).length;
const unlinkedAccountCount = (links: LinkListing[]) => links.filter((link) => !link.factsPersonId).length;
